version: '3'


services:
  db:
    image: postgres:13.3
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  
  app:
    build: ./
    env_file:
      - .env
    ports:
      - 5001:5000
    depends_on:
      - db


volumes:
  pg_data: