"""Create istory table

Revision ID: 8673eb832029
Revises: 24a6b3b7cdc8
Create Date: 2024-07-17 20:53:31.100252

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8673eb832029"
down_revision = "24a6b3b7cdc8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("search_history")
    # ### end Alembic commands ###
