"""Create relation betwin user and history table

Revision ID: 93581d68fa78
Revises: 8673eb832029
Create Date: 2024-07-17 23:15:02.182124

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "93581d68fa78"
down_revision = "8673eb832029"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("search_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])
        batch_op.drop_column("session_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("search_history", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("session_id", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
